SELECT	SP.TENSP AS 'Tên sản phẩm',
		SP.NHASX AS 'Nhà sản xuất',
		FORMAT(SP.GIATIEN, 'C','VI-VN') AS 'Giá tiền',
		CNSP.SLUONGSP AS 'Số lượng còn lại',
		CN.TENCN AS 'Tên chi nhánh'
FROM SANPHAM SP
	INNER JOIN CHINHANH_SANPHAM CNSP
		ON SP.MASP = CNSP.MASP
	INNER JOIN CHINHANH CN
		ON CNSP.MACN = CN.MACN
WHERE SP.TENSP LIKE N'%sữa%'