SELECT	FORMAT(SUM(DH.SLUONG * SP.GIATIEN), 'C', 'VI-VN') AS 'Tổng doanh thu',
		CN.MACN AS 'Mã chi nhánh',
		CN.TENCN AS 'Tên chi nhánh'
FROM DBO.CHITIETDH DH 
	INNER JOIN DBO.SANPHAM SP
		ON DH.MASP = SP.MASP
	INNER JOIN DBO.DONHANG D
		ON D.MADH = DH.MADH
	INNER JOIN NHANVIEN NV
		ON NV.MANV = D.MANV
	INNER JOIN CHINHANH CN
		ON CN.MACN = NV.MACN
GROUP BY CN.MACN, CN.TENCN