SELECT	COUNT(NV.MACN) AS 'Số nhân viên',
		NV.MACN AS 'Mã chi nhánh',
		CN.TENCN AS 'Tên chi nhánh'
FROM NHANVIEN NV 
	LEFT JOIN CHINHANH CN
		ON NV.MACN = CN.MACN
WHERE NV.MACN='CN0007'
GROUP BY NV.MACN, CN.TENCN